### ISSUE TITLE
Miami Crypto Exchange (MCEX) - Security Token Offering

### ISSUE THREAD

**Issue by mpirrongelli** [trustroot/entity-request#1]
The Miami Crypto Exchange (MCEX) plans to be a legal, fully compliant crypto gateway for securities and non-securities tokens between the US and the world, with a focus on Latin America and the Caribbean. Thus, we are a leader in the Market with sustainable plans and cutting edge technologies for the future of the industry.

In partnership with the multi-currency wallet system, Mercury Cash, the MCEX platform allows trading of a wider variety of non-securities and securities, with exclusive service features unique to the industry. Mercury Cash acts as a marketplace for the user wishing to buy and sell or just send and receive different forms of Cryptocurrency.

We offer many levels of entry to meet the needs of every customer.

**Domain:**

https://sto.miami.exchange

* name: Miami Crypto Exchange (MCEX) Security Token Offering

**Entity:**

* legal name: Adventurous Entertainment LLC
* incorporation country: United States
* incorporation state/province: Florida
* incorporation year: 2016
* headquarters country: United States
* headquarters state/province: Florida
* headquarters city: Orlando

**Social**

* contact email: sto@miami.exchange, victor@miami.exchange, marco@mercury.cash
* twitter: twitter.com/miamiexchange
* facebook: facebook.com/miamiexchange
* telegram: https://t.me/mercurycash

**Comment by shayangz** [comment]
Thanks for the report. Your entity has been added to the database. There are a few more steps for being certified. Our team will be in touch with next steps.
